#!/bin/bash

# Generic script to switch Hyprland input configuration based on keyboard connection
# This script is triggered by udev rules

ACTION=$1
CONFIG_DIR="$HOME/.config/hypr"
CONFIG_FILE="$CONFIG_DIR/keyboard-hotswap.conf"
ACTIVE_CONFIG="$CONFIG_DIR/input.conf"
LOG_FILE="/tmp/keyboard-switch.log"

# Function to log messages
log_message() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}

# Load configuration
load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
    else
        log_message "Configuration file not found: $CONFIG_FILE"
        exit 1
    fi
}

# Generate input configuration
generate_input_config() {
    local kb_options="$1"
    local compose_option="compose:caps"

    # Build kb_options string
    if [ ! -z "$kb_options" ]; then
        kb_options="${compose_option},${kb_options}"
    else
        kb_options="${compose_option}"
    fi

    cat <<EOF
# Control your input devices
# Generated by keyboard-hotswap
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts
  kb_layout = us
  kb_options = $kb_options

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Scroll nicely in the terminal
windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)
windowrule = scrolltouchpad 0.2, class:com.mitchellh.ghostty
EOF
}

# Function to reload Hyprland configuration
reload_hyprland() {
    # Check if Hyprland is running
    if pgrep -x "Hyprland" > /dev/null; then
        # Get the Hyprland instance signature
        export HYPRLAND_INSTANCE_SIGNATURE=$(ls -t /tmp/hypr 2>/dev/null | head -n 1 | grep -v lock)

        # Send reload signal to Hyprland
        hyprctl reload
        log_message "Hyprland configuration reloaded"
    else
        log_message "Hyprland is not running, skipping reload"
    fi
}

# Check if external keyboard is connected
is_external_connected() {
    if [ ! -z "$EXTERNAL_KEYBOARD_ID" ]; then
        lsusb | grep -q "$EXTERNAL_KEYBOARD_ID"
        return $?
    else
        return 1
    fi
}

# Main logic
main() {
    load_config

    case "$ACTION" in
        "connected"|"add")
            log_message "External keyboard connected: $EXTERNAL_KEYBOARD_DESC"
            generate_input_config "$EXTERNAL_KB_OPTIONS" > "$ACTIVE_CONFIG"
            reload_hyprland
            ;;
        "disconnected"|"remove")
            log_message "External keyboard disconnected"
            generate_input_config "$LAPTOP_KB_OPTIONS" > "$ACTIVE_CONFIG"
            reload_hyprland
            ;;
        "check")
            # Check if keyboard is connected
            if is_external_connected; then
                log_message "External keyboard detected: $EXTERNAL_KEYBOARD_DESC"
                generate_input_config "$EXTERNAL_KB_OPTIONS" > "$ACTIVE_CONFIG"
            else
                log_message "No external keyboard detected, using laptop configuration"
                generate_input_config "$LAPTOP_KB_OPTIONS" > "$ACTIVE_CONFIG"
            fi
            reload_hyprland
            ;;
        *)
            log_message "Unknown action: $ACTION"
            exit 1
            ;;
    esac
}

# Run main function
main "$@"
exit 0